// LOGIN ACTIONS
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// LOGOUT ACTIONS
export const LOGOUT = 'LOGOUT';

// REGISTER ACTIONS
export const HAS_JUST_REGISTERED = 'HAS_JUST_REGISTERED';